### ISSUE TITLE
Support for Maven Dependency

### ISSUE THREAD

**Issue by saikrishna321** [chemouna/frame-gradle-plugin#22]

**Comment by chemouna** [comment]
:+1:  , Will take a look tonight.

**Comment by saikrishna321** [comment]
:+1:  waiting for it.. May be a method like frameIt("pathToTheFrame","pathToTheInputFile","pathToTheOutPutFile")

**Comment by saikrishna321** [comment]
@chemouna thanks for a quick one. Is there any sample test on how to put this stuff in java code?

**Comment by chemouna** [comment]
for now it works only as a gradle plugin.. what precisely do you need in java code ?

**Comment by saikrishna321** [comment]
Under the gradle file we have this task which does the job.

```
frames {
    inputDir = "screenshots"
    outputDir = "output"
    framesDir = "frames"
    selectedFrame = "galaxy_nexus_port_back.png"
    localTitlesMap =  [
            "en_US": ["from": "Example screenshot title #1", "to": "Example screenshot title #2"],
            "fr_FR": ["from": "Exemple pour titre screenshot #1", "to": "Exemple pour titre screenshot #2"]
    ]

    textColor = "#FFFFFF"
    textSize = 40
    topOffset = 0
}
```

So similar way can i want this be executed under a Main method from java

**Comment by chemouna** [comment]
for now it's written with groovy but maybe take a look at this app https://github.com/f2prateek/device-frame-generator (which android/java code for framing)
